# docker-compose.yml

services:
  webapp:
    build: webapp
    ports:
     - "8888:80"

  database:
    build: database
    environment:
      MYSQL_ROOT_PASSWORD: movie123
    ports:
      - "3306:3306"